# pip install bip-utils

"""
BIP39 / BIP84 Bitcoin Mnemonic Recovery Script

Purpose:
    This script helps recover a BIP39 mnemonic when only a small number of words
    are missing.

Suitable use case:
    1. You know most of your mnemonic words.
    2. Unknown positions are represented by a question mark "?".
    3. You know at least one BTC receiving address generated by the wallet.
    4. The address type is Bitcoin Native SegWit, meaning a bc1q... address.
    5. The derivation path is BIP84:
           m/84'/0'/0'/0/index

Input format:
    Example mnemonic word list:
        ["abandon", "abandon", "?", "abandon", "abandon", "abandon",
         "abandon", "abandon", "abandon", "abandon", "abandon", "?"]

    Example candidate word list:
        ["about", "above", "absent"]

    If the candidate word list is left empty, the script will try all 2048
    English BIP39 words.

Important reminders:
    1. Use this only to recover your own wallet.
    2. It is strongly recommended to run this script on an offline computer.
    3. If a match is found, the full mnemonic will be printed on the screen.
    4. Do not enter a real mnemonic on an online computer, shared computer,
       remote server, or any environment you do not fully trust.
    5. This script does not intentionally write anything to local files.

For anyone who has lost mnemonic words:
    If you are using this script, you may be under serious stress.
    Losing mnemonic words is painful, and that pressure is understandable.
    However, it must also be stated clearly: this kind of problem is usually
    not caused by a technical failure, but by careless backup and storage.

    A mnemonic is effectively the final control key to the wallet assets.
    Once it is lost, leaked, written incorrectly, or stored in the wrong order,
    the assets may become permanently unrecoverable or may be taken by someone else.

    If you manage to recover your wallet this time, treat it as a serious lesson.
    Mnemonic words should be backed up offline, clearly, accurately, redundantly,
    and stored in a secure place. Do not store them only on a phone, computer,
    screenshot, cloud drive, chat history, or browser.
    For crypto assets, the mnemonic is not just a password. It is the asset itself.
"""

import ast
import itertools
import time
from getpass import getpass

from bip_utils import (
    Bip39Languages,
    Bip39MnemonicValidator,
    Bip39SeedGenerator,
    Bip39WordsListGetter,
    Bip44Changes,
    Bip84,
    Bip84Coins,
)
# ============================================================
# Basic information
# ============================================================
print("=" * 70)
print("BIP39 / BIP84 Bitcoin Mnemonic Recovery Tool")
print("=" * 70)
print("Purpose: recover a mnemonic when some words are known and unknown words are marked with ?.")
print("Address type: Bitcoin Native SegWit, meaning bc1q... addresses.")
print("Default path: m/84'/0'/0'/0/index")
print("Note: this script does not write anything to local files.")
print("=" * 70)
print()


# ============================================================
# Read target address
# ============================================================

# The target address is the wallet address you want to match.
# The script will derive addresses from candidate mnemonics and compare them
# against this target address.
target_address = input("Enter the target BTC address, for example bc1q...: ").strip()

if target_address == "":
    raise ValueError("Target address cannot be empty.")

# Basic prefix check.
# Note: this is only a simple warning, not a full Bech32 address validation.
if not target_address.startswith("bc1q"):
    print()
    print("Warning: the address you entered does not start with bc1q.")
    print("This script is designed for Bitcoin Native SegWit addresses, meaning bc1q addresses.")
    print("If your address starts with 1... or 3..., this derivation path may not be suitable.")
    print()


# ============================================================
# Read mnemonic word list
# ============================================================

print()
print("Enter the mnemonic word list.")
print('Known words should be written normally. Unknown words should be written as "?".')
print()
print("Example:")
print('["abandon", "abandon", "?", "abandon", "abandon", "abandon",')
print(' "abandon", "abandon", "abandon", "abandon", "abandon", "?"]')
print()

# ast.literal_eval parses a Python literal safely.
# It is safer than eval because it does not execute arbitrary code.
mnemonic_words = ast.literal_eval(input("Mnemonic word list: ").strip())

if not isinstance(mnemonic_words, list):
    raise ValueError("Mnemonic words must be provided as a list.")

# Normalize all words: convert to lowercase and remove surrounding spaces.
mnemonic_words = [
    str(word).strip().lower()
    for word in mnemonic_words
]

# BIP39 mnemonics can only have 12, 15, 18, 21, or 24 words.
if len(mnemonic_words) not in [12, 15, 18, 21, 24]:
    raise ValueError(
        f"Invalid mnemonic length: {len(mnemonic_words)} words. "
        "It must be 12, 15, 18, 21, or 24 words."
    )


# ============================================================
# Read candidate word list
# ============================================================

print()
print("Enter the candidate word list.")
print('These candidate words will be used to fill every "?" position.')
print()
print("Example:")
print('["about", "above", "absent"]')
print()
print("If you do not know the missing words at all, just press Enter.")
print("If left empty, the script will try all 2048 English BIP39 words.")
print()

candidates_input = input("Candidate word list, or empty: ").strip()


# ============================================================
# Load English BIP39 word list
# ============================================================

# The English BIP39 word list contains 2048 words.
# If the user does not provide a candidate list, the full word list is used.
words_list = Bip39WordsListGetter().GetByLanguage(Bip39Languages.ENGLISH)
bip39_words = [
    words_list.GetWordAtIdx(i)
    for i in range(words_list.Length())
]
bip39_words_set = set(bip39_words)
# ============================================================
# Process candidate words
# ============================================================
if candidates_input == "":
    # If no candidate words are provided, use the full English BIP39 word list.
    candidates = bip39_words
else:
    # If candidate words are provided, parse them as a Python list.
    candidates = ast.literal_eval(candidates_input)

    if not isinstance(candidates, list):
        raise ValueError("Candidate words must be provided as a list.")

    candidates = [
        str(word).strip().lower()
        for word in candidates
    ]

if len(candidates) == 0:
    raise ValueError("Candidate word list cannot be empty.")
# ============================================================
# Validate known mnemonic words and candidate words
# ============================================================

# Check known mnemonic words.
# The question mark "?" means an unknown word and does not need to be
# in the BIP39 word list.
for index, word in enumerate(mnemonic_words, start=1):
    if word == "?":
        continue

    if word not in bip39_words_set:
        raise ValueError(f"Word #{index} is not a valid English BIP39 word: {word}")

# Check that all candidate words are valid English BIP39 words.
for word in candidates:
    if word not in bip39_words_set:
        raise ValueError(f"Candidate word is not a valid English BIP39 word: {word}")
# ============================================================
# Find unknown word positions
# ============================================================
# missing_positions uses zero-based indexes for easier programming.
# When printing positions for the user, we add 1 to make them human-friendly.
missing_positions = [
    index
    for index, word in enumerate(mnemonic_words)
    if word == "?"
]
if len(missing_positions) == 0:
    raise ValueError('The mnemonic word list contains no "?"; there is nothing to recover.')
# ============================================================
# Read BIP39 passphrase and address index range
# ============================================================
print()
# The BIP39 passphrase is not the same as the wallet app login password.
# It is an optional extra phrase that may have been set when creating the wallet.
# If you did not set a BIP39 passphrase, just press Enter.
passphrase = getpass("BIP39 passphrase, or press Enter if none: ")

# Common BIP84 receiving address paths:
#
#   m/84'/0'/0'/0/0
#   m/84'/0'/0'/0/1
#   m/84'/0'/0'/0/2
#   ...
#
# start_index tells the script where to begin checking.
start_index_input = input("Enter start index, default 0: ").strip()

if start_index_input == "":
    start_index = 0
else:
    start_index = int(start_index_input)

# address_count tells the script how many consecutive addresses to check.
# By default, it checks index 0 through 19.
address_count_input = input("Enter number of addresses to check, default 20: ").strip()

if address_count_input == "":
    address_count = 20
else:
    address_count = int(address_count_input)

if start_index < 0:
    raise ValueError("Start index cannot be less than 0.")

if address_count <= 0:
    raise ValueError("Address count must be greater than 0.")


# ============================================================
# Calculate total number of combinations
# ============================================================

# If there is 1 "?" and 100 candidate words, total combinations = 100.
# If there are 2 "?" positions and 100 candidate words, total combinations = 100 * 100.
#
# If no candidate list is provided and the script uses all 2048 BIP39 words:
#
#   1 unknown word = 2,048 combinations
#   2 unknown words = 2,048 * 2,048 = 4,194,304 combinations
#   3 unknown words = 2,048 * 2,048 * 2,048 = 8,589,934,592 combinations
#
# Therefore, if 3 or more words are missing and you have no candidate list,
# the search will usually be extremely slow.
total_combinations = len(candidates) ** len(missing_positions)

# Safety limit to prevent accidentally starting an extremely large search.
# You may increase this value manually if you are sure you want to run a larger search.
max_combinations = 5_000_000


# ============================================================
# Print task summary
# ============================================================

print()
print("=" * 70)
print("Starting search")
print("=" * 70)
print(f"Target address       : {target_address}")
print(f"Mnemonic length      : {len(mnemonic_words)}")
print(f"Unknown word count   : {len(missing_positions)}")
print(f"Unknown positions    : {[pos + 1 for pos in missing_positions]}")
print(f"Candidate word count : {len(candidates)}")
print(f"Total combinations   : {total_combinations:,}")
print(f"Search path          : m/84'/0'/0'/0/{start_index} ~ {start_index + address_count - 1}")
print("=" * 70)
print()

if total_combinations > max_combinations:
    raise ValueError(
        f"Too many combinations: {total_combinations:,}. "
        f"The current limit is {max_combinations:,}. "
        'Please reduce the candidate word list or reduce the number of "?" positions.'
    )
# ============================================================
# Start enumeration and checking
# ============================================================
start_time = time.time()
checked_count = 0
valid_mnemonic_count = 0
found = False
# itertools.product(candidates, repeat=len(missing_positions))
# generates every possible combination of candidate words.
#
# Example:
#
#   candidates = ["about", "above"]
#
# If there are two "?" positions, it will try:
#
#   about about
#   about above
#   above about
#   above above
#
for replacement_words in itertools.product(candidates, repeat=len(missing_positions)):
    checked_count += 1

    # Make a copy of the mnemonic template.
    test_words = mnemonic_words.copy()

    # Replace each "?" position with the current candidate combination.
    for position, replacement_word in zip(missing_positions, replacement_words):
        test_words[position] = replacement_word
    # Join the word list into a complete mnemonic string.
    mnemonic = " ".join(test_words)

    # First, check the BIP39 checksum.
    #
    # This is very important because most combinations are not valid mnemonics.
    # Invalid mnemonics do not need address derivation, which saves a lot of time.
    is_valid = Bip39MnemonicValidator(Bip39Languages.ENGLISH).IsValid(mnemonic)
    if not is_valid:
        # Print progress every 100,000 checked combinations.
        # Progress is printed even when the current combination is invalid.
        if checked_count % 100_000 == 0:
            elapsed = time.time() - start_time

            print(
                f"Checked {checked_count:,} / {total_combinations:,}, "
                f"valid mnemonics {valid_mnemonic_count:,}, "
                f"elapsed {elapsed:.2f} sec"
            )

        continue

    valid_mnemonic_count += 1

    # Only after checksum validation do we generate the seed.
    seed_bytes = Bip39SeedGenerator(mnemonic).Generate(passphrase)

    # Build the BIP84 derivation context.
    #
    # Path prefix:
    #
    #   m/84'/0'/0'/0
    #
    # Meaning:
    #   84' = BIP84
    #   0'  = Bitcoin mainnet
    #   0'  = account 0
    #   0   = external receiving address chain
    receive_ctx = (
        Bip84.FromSeed(seed_bytes, Bip84Coins.BITCOIN)
        .Purpose()
        .Coin()
        .Account(0)
        .Change(Bip44Changes.CHAIN_EXT)
    )

    # Check multiple address indexes.
    #
    # By default, it checks:
    #
    #   m/84'/0'/0'/0/0
    #   m/84'/0'/0'/0/1
    #   ...
    #   m/84'/0'/0'/0/19
    #
    for address_index in range(start_index, start_index + address_count):
        address = receive_ctx.AddressIndex(address_index).PublicKey().ToAddress()

        # If the derived address matches the target address, the mnemonic was found.
        if address == target_address:
            path = f"m/84'/0'/0'/0/{address_index}"

            print()
            print("=" * 70)
            print("Match found")
            print("=" * 70)
            print(f"Mnemonic   : {mnemonic}")
            print(f"Passphrase : {passphrase!r}")
            print(f"Path       : {path}")
            print(f"Address    : {address}")
            print("=" * 70)
            found = True
            break
    if found:
        break
    # Print progress every 100,000 checked combinations.
    if checked_count % 100_000 == 0:
        elapsed = time.time() - start_time

        print(
            f"Checked {checked_count:,} / {total_combinations:,}, "
            f"valid mnemonics {valid_mnemonic_count:,}, "
            f"elapsed {elapsed:.2f} sec"
        )
# ============================================================
# Print final result
# ============================================================
print()
print("=" * 70)
if found:
    print("Search finished: matching mnemonic found.")
else:
    print("Search finished: no matching result found.")
    print()
    print("Possible reasons:")
    print("1. The candidate word list does not contain the real missing word.")
    print('2. The "?" positions are wrong.')
    print("3. The target address was not generated from this mnemonic.")
    print("4. The BIP39 passphrase is wrong.")
    print("5. The address does not use the BIP84 path m/84'/0'/0'/0/index.")
    print("6. The index search range is too small; try increasing the address count.")

print(f"Total checked combinations : {checked_count:,}")
print(f"Valid mnemonics            : {valid_mnemonic_count:,}")
print(f"Total elapsed time         : {time.time() - start_time:.2f} sec")
print("=" * 70)
